### PR TITLE
jack module: set soundpipe to JACK sample rate

### PR DESCRIPTION
**Pull request by belm0**
I'm not sure whether setting this in sp_jack_process() is too late for other modules, which may need the correct sample rate at init.

Otherwise the soundpipe client needs to access the JACK API directly to get the rate, in which case the jack example should be modified to show this (vs. current hard-coded 96000).

### CODE REVIEW

**Comment by belm0** [comment]
OK it's fairly obvious that setting the soundpipe rate in process() as I've done here is not sufficient.

If the client code has to do it, there's the mess of giving it access to the jack client.. which isn't created until process() anyway.  I guess the client code will have to make a temporary jack client just to get the sample rate.

**Comment by belm0** [comment]
Updated to query sample rate in client code.

**Comment by belm0** [comment]
A side effect is that auto-start of jackd no longer works (at least as I observe on OS X).  It seems related to the timing of calling jack_client_open() (in jack sp module) immediately following jack_client_close() (in sp client after obtaining sample rate).

**A preferable API would be to have sp_jack_process accept a jack client object.  Then programs could open a single jack client, as well as customize any jack parameters.**

**Comment by PaulBatchelor** [comment]
Is this ready to be merged? I'm happy to merge your code if it is helpful for you since it is a small localized fix, but this is a deprecated part of Soundpipe.

**Comment by PaulBatchelor** [comment]
see comment in #99. both the JACK and Pi modules for realtime audio have been removed from Soundpipe.

**Pull request closed without merging**
