### PR TITLE
more Float or double

### PR DESCRIPTION
**Pull request by fennecdjay**
put USE_DOUBLE in soundpipe.h, it is no more in CFLAGS
put the content of spfloat.h in it also
all math function now prefixed with sp_, so they use good type.
Let faust module untouched for now, but they would need to be generated with -double when compiling with double

### CODE REVIEW

**Comment by PaulBatchelor** [comment]
Like I said before, I don't like these lowercase macros. Also, this PR adds
way too much unnecessary code and touches way too many files.

**Comment by fennecdjay** [comment]
I see.
Would it be OK to UPPERCASE those macros, and split the PR so that it hits only a few files each time?

**Comment by PaulBatchelor** [comment]
No, because this would make soundpipe more centralized. Also, this adds a
degree of complication that I find unnecessary. Perceptually, the change in
precision doesn't make much of a difference. Most of the DSP algorithms
here don't really benefit from the extra numerical precision.

On Nov 3, 2016 10:31, "Jérémie Astor" <notifications@github.com> wrote:

I see.
Would it be OK to UPPERCASE those macros, and split the PR so that it hits
only a few files each time?

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/PaulBatchelor/Soundpipe/pull/84#issuecomment-258215388>,
or mute the thread

**Comment by PaulBatchelor** [comment]
If you're going to be anything to soundpipe, please make a GitHub issue or
a trello card before doing anything major like this. Otherwise, I'm
probably going to close your PR requests.

**Pull request closed without merging**
