### PR TITLE
Added tests and docgen edits

### PR DESCRIPTION
**Pull request by narner**

### CODE REVIEW

**Comment by PaulBatchelor** [comment]
phasor test is wrong in the compute cycle, as you are just filling it with zeros.

**Comment by narner** [comment]
@PaulBatchelor Whenever I execute ./run.bin, I seem to get a a different MD5 output every-time for the noise test. Mind taking a closer look at that one?

**Comment by PaulBatchelor** [comment]
@narner on it...

**Comment by PaulBatchelor** [comment]
You forgot to get rid of sp_create, which may be doing some funky things. This is also true for t_pareq.

You'll also need to stick "sp_rand(sp, 0);" in your tests, as this is seeding the internal RNG. There are many tests that use this. Look at something like t_butbp for reference.

**Pull request merged**
