### PR TITLE
ptrack update for normal amplitude

### PR DESCRIPTION
**Pull request by aure**

### CODE REVIEW

**Comment by PaulBatchelor** [comment]
That exp is expensive, but I'll merge it anyways.

**Comment by aure** [comment]
Sorry, how will you avoid using exp?

**Comment by PaulBatchelor** [comment]
See the ampdb function in Sporth. I'm not sure how/why it works but it
does.

**Comment by aure** [comment]
I used the Sporth as my model.  It uses exp.

**Comment by PaulBatchelor** [comment]
Oh. I could be going crazy then. Nvm.

**Comment by PaulBatchelor** [comment]
confirmed. going crazy. carry on...

**Pull request merged**
