### PR TITLE
Fix sparec.lua

### PR DESCRIPTION
**Pull request by fennecdjay**
It looks like sparec.lua forgets about output value.
I noticed it because last commits on your dev branch break Gwion build system on Travi-CI.
You can watch the log [here](https://travis-ci.org/fennecdjay/Gwion/jobs/209700119#L2470).
Would you please consider merging this?

NOTE: I checked it did not break your doc system.

### CODE REVIEW

**Comment by PaulBatchelor** [comment]
Sparec doesn't have any outputs, which is why noutouts is 0. It should have similar behavior to tblrec.

**Comment by PaulBatchelor** [comment]
It broke my sporth generator in a similar way. I'm going to see if tblrec did the same thing.

**Comment by fennecdjay** [comment]
> It broke my sporth generator in a similar way

Do you mean this PR or your last commits?

Please let me know, Ill be glad both to help and get it fixed for everyone.
On my side, tblrec is OK. (yet it has noutputs =1).

**Comment by PaulBatchelor** [comment]
Despite the fact that it's there, tblrec doesn't actually have an output. So that's a mistake on my part.
Sparec doesn't write anything to the out variable either. It's documentation is correct, but when noutputs=0 it screws up because it writes a function without the output variable. 

One line of thought is to lop off the output variable since it doesn't do anything. But having dummy variables is already precedent for inputs, and I'd like that to be consistent for outputs. It's a little dumb, but it's not worth the work to undo that conscious choice I made years ago.

I think what I'll do is change the behavior of sparec and tblrec so they do intentionally push a copy of the signal they are recording, as that is the most likely use case (the sporth "print" ugen uses this behavior as well). Best of both worlds in that case. It'll break a few patches on my end, but it shouldn't be too bad.

Thank you for your attention to this!

**Comment by fennecdjay** [comment]
So maybe we can close this PR.

**Comment by PaulBatchelor** [comment]
Can you try the pushes I made first? Just need to see if it fixes your original problem.

**Comment by fennecdjay** [comment]
It works for me.
Thank you for the quick reaction.

**Pull request closed without merging**
