### PR TITLE
Idea for simple index page

### PR DESCRIPTION
**Pull request by aure**
If you adopt the convention that the first line of the description is a short summary of the module, then this method could give some pretty nice results.  Creating the pull request for feedback, not necessarily to merge unless you want to use it and hack at it a bit.

### CODE REVIEW

**Comment by PaulBatchelor** [comment]
I like it. that's a good convention, and it saves the hassle of having to make a "short description" category.

**Comment by aure** [comment]
I can change docs as I run across them.  10 or so a day and we're done real soon.

**Comment by PaulBatchelor** [comment]
Sounds good. Also, feel free to tighten up the language in spots where you feel it is needed. I trust your judgement.

**Comment by aure** [comment]
Merge and I'll push small changes directly then.

**Comment by PaulBatchelor** [comment]
I merged it already?

**Pull request merged**
